runtime: php82
env: standard
entrypoint: serve public/index.php

runtime_config:
  document_root: public

handlers:
  - url: "/favicon\\.ico"
    static_files: public/favicon.ico
    upload: public/favicon\\.ico

  - url: "/(.+\\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))"
    static_files: public/\1
    upload: public/(.+\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))

  - url: /.*
    script: auto
