runtime: php82
env: standard
entrypoint: serve public/index.php

runtime_config:
  document_root: public

handlers:
  - url: "/favicon\\.ico"
    static_files: public/favicon.ico
    upload: public/favicon\\.ico

  - url: "/(.+\\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))"
    static_files: public/\1
    upload: public/(.+\.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot))

  - url: /.*
    script: auto

env_variables:
  APP_ENV: production
  APP_DEBUG: true
  APP_URL: https://projet-2-siao-456710.ew.r.appspot.com
  APP_KEY: base64:oZ9Y3JEnvs+xB7tXoZYy3aAh+kM3DhCJyJPobWX3wXs=

  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_SOCKET: /cloudsql/projet-2-siao-456710:europe-west1:bddsiao
  DB_PORT: 3306
  DB_DATABASE: siao
  DB_USERNAME: siao
  DB_PASSWORD: tototititutu83!

  LOG_CHANNEL: stack
  LOG_LEVEL: debug
  LOG_STORAGE_PATH: /tmp
  VIEW_COMPILED_PATH: /tmp

beta_settings:
  cloud_sql_instances: projet-2-siao-456710:europe-west1:bddsiao
